# model params
num_layers: 3
num_heads: 8
model_dim: 64
hidden_dim: 128
decoder_hidden_dim: 128
dropout: 0.0
sample_k: 20
aggregation: 'avg'
function_type: 2
hyper_scales: [1, 'adaptive']

# input/output params
past_length: 10
future_length: 20
inputs: ['pos_x', 'pos_y', 'vel_x', 'vel_y']
pred_rel: False

# training params
num_epochs: 100
lr: 0.0005
clip_grad: null
batch_size: 64
scheduler_type: CosineAnnealingLR
milestones: [100, 200]
decay_gamma: 0.5